version: '3.8'

services:
  db:
    image: postgres:13
    container_name: turbo_repair_db
    environment:
      POSTGRES_USER: mastermind
      POSTGRES_PASSWORD: ujif1234
      POSTGRES_DB: turbo_repair
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

